allow to disable API generation in rock-make-doc using an environment variable

diff --git a/bin/rock-make-doc b/bin/rock-make-doc
--- a/bin/rock-make-doc
+++ b/bin/rock-make-doc
@@ -53,29 +53,31 @@ fi
 set -e
 
 tempdir=$(mktemp -d)
-echo "generating the API documentation from the autoproj packages"
-cd $autoproj_dir
-autoproj doc
-mkdir -p $target_dir
-echo "copying API documentation to $target_dir/api"
-cp -r install/doc $target_dir/api
-
-autoproj_version=`$GEM_HOME/bin/autoproj --version | sed 's/autoproj.*v//'`
-autoproj_api_dir=$GEM_HOME/doc/autoproj-$autoproj_version
-if test -d $autoproj_api_dir; then
-    echo "copying autoproj API documentation to $target_dir/api/autoproj"
-    cp -r $autoproj_api_dir/rdoc $target_dir/api/autoproj
-else
-    echo "could not find the autoproj API in $autoproj_api_dir"
-fi
-
-autobuild_version=`$GEM_HOME/bin/autobuild --version | sed 's/autobuild.*v//'`
-autobuild_api_dir=$GEM_HOME/doc/autobuild-$autobuild_version
-if test -d $autobuild_api_dir; then
-    echo "copying autobuild API documentation to $target_dir/api/autobuild"
-    cp -r $autobuild_api_dir/rdoc $target_dir/api/autobuild
-else
-    echo "could not find the autobuild API in $autobuild_api_dir"
+if ! test "$ROCK_DOC_API" = "0"; then
+    echo "generating the API documentation from the autoproj packages"
+    cd $autoproj_dir
+    autoproj doc
+    mkdir -p $target_dir
+    echo "copying API documentation to $target_dir/api"
+    cp -r install/doc $target_dir/api
+    
+    autoproj_version=`$GEM_HOME/bin/autoproj --version | sed 's/autoproj.*v//'`
+    autoproj_api_dir=$GEM_HOME/doc/autoproj-$autoproj_version
+    if test -d $autoproj_api_dir; then
+        echo "copying autoproj API documentation to $target_dir/api/autoproj"
+        cp -r $autoproj_api_dir/rdoc $target_dir/api/autoproj
+    else
+        echo "could not find the autoproj API in $autoproj_api_dir"
+    fi
+    
+    autobuild_version=`$GEM_HOME/bin/autobuild --version | sed 's/autobuild.*v//'`
+    autobuild_api_dir=$GEM_HOME/doc/autobuild-$autobuild_version
+    if test -d $autobuild_api_dir; then
+        echo "copying autobuild API documentation to $target_dir/api/autobuild"
+        cp -r $autobuild_api_dir/rdoc $target_dir/api/autobuild
+    else
+        echo "could not find the autobuild API in $autobuild_api_dir"
+    fi
 fi
 
 echo "creating rock's main documentation"
